# Scraping player statistics

This notebook will cover scraping player statistics from https://www.transfermarkt.co.uk/. These player statistics will later be used as features in combination with data pertaining to individual matches.

In [44]:
from selenium import webdriver

In [236]:
browser = webdriver.Chrome("./chromedriver")

In [3]:
browser.get("https://www.transfermarkt.co.uk/")

In [49]:
# search for a country
search_base_url = "https://www.transfermarkt.co.uk/schnellsuche/ergebnis/schnellsuche?query="
country = "ivory coast"
year = "2014"
browser.get(search_base_url + country.lower().replace(" ","+"))

In [50]:
# get first result
team_base_url = browser.find_element_by_class_name("odd").find_element_by_css_selector('a[class="vereinprofil_tooltip tooltipstered"]').get_attribute("href")

In [51]:
# go to specific year
browser.get(team_base_url + "?saison_id=" + str(int(year) - 1))

In [62]:
# search roster for player 
players1 = browser.find_element_by_class_name("items").find_elements_by_css_selector('tr[class="odd"]')
players2 = browser.find_element_by_class_name("items").find_elements_by_css_selector('tr[class="even"]')
players = players1 + players2

In [89]:
def get_name_link_age_value(player_element):
    name = player_element.find_element_by_class_name("hauptlink").text
    link = player_element.find_element_by_class_name("hauptlink").find_element_by_tag_name("a").get_attribute("href")
    age = player_element.find_element_by_css_selector('td[class="zentriert"]').text
    value = player_element.find_element_by_css_selector('td[class="rechts hauptlink"]').text
    return [name, link, age, value]

In [90]:
player_data = list(map(get_name_link_age_value, players))

In [94]:
import pandas as pd

header = ["name","link","age","value"]
df = pd.DataFrame(player_data, columns=header)

In [95]:
df

,name,link,age,value
0,Boubacar Copa,https://www.transfermarkt.co.uk/boubacar-copa/...,33,£1.35m
1,Badra Ali Sangaré,https://www.transfermarkt.co.uk/badra-ali-sang...,27,
2,Kolo Touré,https://www.transfermarkt.co.uk/kolo-toure/pro...,32,£5.40m
3,Sol Bamba,https://www.transfermarkt.co.uk/sol-bamba/prof...,28,£1.80m
4,Arthur Boka,https://www.transfermarkt.co.uk/arthur-boka/pr...,30,£1.80m
5,Constant Djakpa,https://www.transfermarkt.co.uk/constant-djakp...,26,£630k
6,Brice Dja Djédjé,https://www.transfermarkt.co.uk/brice-dja-djed...,22,£3.15m
7,Didier Zokora,https://www.transfermarkt.co.uk/didier-zokora/...,32,£3.60m
8,Jean-Jacques Gosso,https://www.transfermarkt.co.uk/jean-jacques-g...,30,£1.35m
9,Ismaël Diomandé,https://www.transfermarkt.co.uk/ismael-diomand...,20,£450k
10,Jean-Daniel Akpa Akpro,https://www.transfermarkt.co.uk/jean-daniel-ak...,20,£1.58m
11,Jean Michaël Seri,https://www.transfermarkt.co.uk/jean-michael-s...,21,
12,Salomon Kalou,https://www.transfermarkt.co.uk/salomon-kalou/...,27,£6.75m
13,Cyriac,https://www.transfermarkt.co.uk/cyriac/profil/...,22,£1.80m
14,Lacina Traoré,https://www.transfermarkt.co.uk/lacina-traore/...,23,£14.40m
15,Didier Ya Konan,https://www.transfermarkt.co.uk/didier-ya-kona...,29,£4.50m
16,Giovanni Sio,https://www.transfermarkt.co.uk/giovanni-sio/p...,24,£1.80m
17,Mandé Sayouba,https://www.transfermarkt.co.uk/mande-sayouba/...,20,£270k
18,Sylvain Gbohouo,https://www.transfermarkt.co.uk/sylvain-gbohou...,24,
19,Benjamin Angoua,https://www.transfermarkt.co.uk/benjamin-angou...,26,£1.80m
20,Ousmane Viera,https://www.transfermarkt.co.uk/ousmane-viera/...,26,£1.53m
21,Siaka Tiéné,https://www.transfermarkt.co.uk/siaka-tiene/pr...,31,£900k
22,Serge Aurier,https://www.transfermarkt.co.uk/serge-aurier/p...,20,£5.40m
23,Cheik Tioté,https://www.transfermarkt.co.uk/cheik-tiote/pr...,27,£9.45m
24,Geoffroy Serey Dié,https://www.transfermarkt.co.uk/geoffroy-serey...,28,£2.25m
25,Romaric,https://www.transfermarkt.co.uk/romaric/profil...,30,£900k
26,Yaya Touré,https://www.transfermarkt.co.uk/yaya-toure/pro...,30,£32.40m
27,Abdul Razak,https://www.transfermarkt.co.uk/abdul-razak/pr...,20,
28,Gervinho,https://www.transfermarkt.co.uk/gervinho/profi...,26,£9.45m
29,Max Gradel,https://www.transfermarkt.co.uk/max-gradel/pro...,25,£3.60m
30,Seydou Doumbia,https://www.transfermarkt.co.uk/seydou-doumbia...,25,£20.70m
31,Wilfried Bony,https://www.transfermarkt.co.uk/wilfried-bony/...,24,£10.80m
32,Didier Drogba,https://www.transfermarkt.co.uk/didier-drogba/...,35,£2.70m
33,Mathis Bolly,https://www.transfermarkt.co.uk/mathis-bolly/p...,22,£675k

In [161]:
all_matches_df = pd.read_csv("data/espn_data_230618_all.csv")

In [237]:
world_cup_years = ["2014","2010","2006","2002","1998","1994","1990","1986","1982","1978"]

for year in world_cup_years:
    print(year)
    # filter dataframe
    year_matches_df = all_matches_df[all_matches_df.year == int(year)]
    team_list = list(set(list(year_matches_df.Team1.values)+list(year_matches_df.Team2.values)))
    get_player_stats_for_year(team_list,year)

1998
Yugoslavia
Paraguay
England
Chile
Nigeria
Croatia
Italy
Argentina
Cameroon
South Africa
Norway
United States
Mexico
South Korea
Jamaica
Saudi Arabia
Colombia
France
Netherlands
Germany
Bulgaria
Romania
Austria
Denmark
Scotland
Morocco
Spain
Japan
Iran
Belgium
Tunisia
Brazil
1994
Greece
Nigeria
Italy
Argentina
Cameroon
Norway
United States
Mexico
South Korea
Saudi Arabia
Colombia
Netherlands
Germany
Bulgaria
Republic of Ireland
Romania
Russia
Morocco
Switzerland
Spain
Bolivia
Sweden
Belgium
Brazil
1990
Yugoslavia
England
Costa Rica
Czechoslovakia
Soviet Union
Egypt
Italy
Cameroon
Argentina
United States
South Korea
Uruguay
Colombia
United Arab Emirates
Netherlands
Republic of Ireland
Romania
Austria
Scotland
Spain
Germany FR
cant find: Germany FR, 1990
Sweden
Belgium
Brazil
1986
Paraguay
England
Soviet Union
Canada
Italy
Argentina
Algeria
Mexico
South Korea
Uruguay
Northern Ireland
Portugal
France
Poland
Bulgaria
Denmark
Scotland
Morocco
Spain
Germany FR
cant find: Germany FR, 1986
Hungary
Belgium
Iraq
Brazil
1982
Yugoslavia
Chile
England
Kuwait
Czechoslovakia
Soviet Union
Italy
Cameroon
Argentina
Algeria
Northern Ireland
Honduras
El Salvador
France
Poland
Peru
Austria
Scotland
Spain
Germany FR
cant find: Germany FR, 1982
Hungary
New Zealand
Belgium
Brazil
1978
Spain
Germany FR
cant find: Germany FR, 1978
Hungary
Sweden
France
Brazil
Poland
Netherlands
Scotland
Mexico
Austria
Peru
Iran
Tunisia
Italy
Argentina

In [214]:
team_list

['Spain',
 'Germany FR',
 'Hungary',
 'Sweden',
 'France',
 'Brazil',
 'Poland',
 'Netherlands',
 'Scotland',
 'Mexico',
 'Austria',
 'Peru',
 'Iran',
 'Tunisia',
 'Italy',
 'Argentina']

In [232]:
def get_player_stats_for_year(team_list, year):
    year_stats = []
    for team in team_list:
        print(team)
        try:
            year_stats += get_player_stats_for_team(team, year)
        except:
            print("cant find: "+ team + ", " + year)
            continue
    df = pd.DataFrame(year_stats, columns=["name","link","age","value"])
    df.to_csv("data/teams/"+year+".csv")

In [221]:
def get_player_stats_for_team(team, year):
    # search for a country
    search_base_url = "https://www.transfermarkt.co.uk/schnellsuche/ergebnis/schnellsuche?query="
    browser.get(search_base_url + team.lower().replace(" ","+"))
    # get first result
    clubs_div = get_clubs_div()
    team_base_url = clubs_div.find_element_by_class_name("odd").find_element_by_css_selector('a[class="vereinprofil_tooltip tooltipstered"]').get_attribute("href")
    # go to specific year
    browser.get(team_base_url + "?saison_id=" + str(int(year) - 1))
    # get player data
    players1 = browser.find_element_by_class_name("items").find_elements_by_css_selector('tr[class="odd"]')
    players2 = browser.find_element_by_class_name("items").find_elements_by_css_selector('tr[class="even"]')
    players = players1 + players2
    player_data = list(map(get_name_link_age_value, players))
    return player_data

In [195]:
"clubs" in browser.find_elements_by_class_name("box")[3].find_element_by_class_name("table-header").text.lower()

True

In [196]:
browser.find_elements_by_class_name("box")[3].text.lower()

'search results: clubs - 11 hits\n  club\ncountry squad\ntotal market value\ntransfers stadium forum\nbrazil\n23 £882.90m    \nbrazil u20\n22 £45.88m    \nsanat naft fc\npersian gulf pro league\n26 £6.23m    \nbrazil u17\n8 £4.55m    \nball school moskau\n2 £90k    \nbrazil u23\n0 -    \nsv brazil juniors\n1 -    \nbrazil u15\n20 -    \nbrazil olympic team\n0 -    \nbrazil international football academy\n0 -    \n1 2      '

In [208]:
def get_clubs_div():
    divs = browser.find_elements_by_class_name("box")
    for div in divs:
        try:
            if "clubs" in div.find_element_by_class_name("table-header").text.lower():
                return div
        except:
            continue
    return